name: Upload video artifact
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install ffmpeg
        run: sudo apt install ffmpeg
      - name: Record video
        run: ffmpeg -f x11grab -video_size 640x480 -i :0.0 video.mp4
      - name: Upload video artifact
        uses: actions/upload-artifact@v3
        with:
          name: video
          path: video.mp4
